### PR TITLE
pipelines support

### PR DESCRIPTION
**Pull request by chutzimir**
- Site awareness for Forwarders
- Pipelines support
- Align the parameters for style

### CODE REVIEW

**Comment by chutzimir** [comment]
This is on top of !56, hence the extra commit.

**Comment by jorritfolmer** [comment]
Hmm apologies I already merged the site awareness PR. Can you rebase on top of the current master and only include the parallelIngestion stuff?

**Comment by chutzimir** [comment]
> Hmm apologies I already merged the site awareness PR. Can you rebase on top of the current master and only include the parallelIngestion stuff?

Here you go!

**Comment by jorritfolmer** [comment]
Thanks again! Merged in 2ad63d923dc87619eb42b6a1d3f53e470a384c7c

**Pull request closed without merging**
