### PR TITLE
(WIP) Convert to PDK

### LINKED ISSUE #39: Convert module to utilize PDK
In order to get a PDK badge and also keep up-to-date with the latest development standards for puppet modules it would be best to convert this module into a pdk compatible one.  If you have no problems with this i can start on the work for this.

### PR DESCRIPTION
**Pull request by TraGicCode**
This converts the module using the `pdk convert` mechanism and then fixing the issues from rubocop and puppet-lint.

Let me know if you have any questions.

Closes #39

### CODE REVIEW

**Comment by TraGicCode** [comment]
Looks like you support some really old versions of puppet.  Does this still hold true?

**Comment by jorritfolmer** [comment]
Yes unless there are good reasons not to

**Comment by TraGicCode** [comment]
From a maintainability perspective i would suggest dropping support from the metadata.json the puppet versions that even puppet themselves no longer support and have urged users to upgrade past.  What are your thoughts on this?

**Comment by TraGicCode** [comment]
Based off the initial run of these tests it looks like Puppet 4 ( Puppet 6 is the latest ) might be the minimum version supported with the PDK.

I'm going to get more information on this and will get back to you.

**Comment by TraGicCode** [comment]
I confirmed with @davids and in order to utilize PDK the minimum puppet version supported it can work with is Puppet 4.  

Up to you what you wanna do with this now @jorritfolmer .  I can kill this PR & branch if you like.

**Comment by DavidS** [comment]
@TraGicCode @jorritfolmer the module can very well support versions prior to puppet 4 even when using the PDK templates.

**Comment by jorritfolmer** [comment]
If I understand it correctly:

1. `strict` on anything below Puppet 4 will fail because https://tickets.puppetlabs.com/browse/PUP-4066 . This accounts for the one failed test 202.7. Perhaps we could skip the strict on this version.

2. The other tests (202.1 -> 202.6) fail because gem `puppet-module-posix-default` doesn't exist  for Ruby versions below 2.1. This doesn't seem fixable if we want to test old Puppet versions with their correspondingly old Ruby versions. How do we fix this?

What I like about the new testing framework is that it actually test against the platform images we're declaring in the metadata.json (except Windows perhaps)

What I don't like is the cost-benefit of it. We gain platform testing but no new functionality at the cost of dropping support for versions that I know for a fact are still being used in the wild (anecdotal, n=2)

**Comment by TraGicCode** [comment]
Closing since i've moved on to other things

**Pull request closed without merging**
